# Generated by Django 5.0.6 on 2024-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pricing_amount', models.FloatField()),
                ('pricing_currency', models.CharField(max_length=10)),
                ('availability_quantity', models.IntegerField()),
                ('availability_timestamp', models.DateTimeField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
